language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   
before_install:
   - cpanm --notest --quiet Module::Install::CPANfile
   - cpanm --notest --quiet Module::Install::AuthorTests
   - cpanm --notest --quiet Net::OpenID::Consumer

notifications:
   irc:
      channels:
         - irc.freenode.org#chupei.pm
         
