sudo: required

language: perl
perl:
   - "5.19"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq libgmp-dev
   - '(echo yes; echo o conf prerequisites_policy follow;echo o conf commit) | cpan'
   - cpanm --notest --quiet Module::Install::CPANfile
   - cpanm --notest --quiet Module::Install::AuthorTests

notifications:
   irc:
      channels:
         - irc.freenode.org#chupei.pm
